taxi_data:
  outputs:
    dev:
      dataset: taxi_data
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: /opt/dbt_account_v2.json
      location: europe-central2
      method: service-account
      priority: interactive
      project: tribal-logic-361320
      threads: 1
      type: bigquery
  target: dev
