
version: 2

models:
  - name: stg_trips
    description: "Staging dataset containing trips data"
    columns:
      - name: VendorID
        description: "ID of taxi vendor"
        tests:
          - not_null
          - accepted_values:
              values: [1, 2, 5, 6]
              quote: false
       
      - name: tpep_pickup_datetime
        description: 'Date and time of trip start'
        tests:
          - not_null
      - name: tpep_dropoff_datetime
        description: 'Date and time of trip end'
        tests:
          - not_null
      - name: passenger_count
        description: 'Number of passengers in taxi'
      - name: trip_distance
        description: 'Distance of taxi trip in miles'
      - name: payment_type
        description: 'Type of payment method'
        tests:
          - accepted_values:
              values: [0 ,1, 2, 3, 4, 5]
              quote: false
      - name: total_amount
        description: 'The total amount charged to passengers. Does not include cash tips'
      - name: PULocationID
        description: 'ID of trip start location'
        tests:
          - relationships:
              to: ref('stg_zones')
              field: LocationID
      - name: DOLocationID
        description: 'ID of trip end location'
        tests:
          - relationships:
              to: ref('stg_zones')
              field: LocationID
      - name: year_from_file
        description: 'Year taken from filename'
      - name: month_from_file
        description: 'Month taken from filename'
      



  - name: stg_zones
    description: "Staging dataset containing zones data"

